# примеры API-запросов



# получение объявлений
GET http://127.0.0.1:8000/api/v1/advertisements/
Content-Type: application/json

###

# создание объявления
POST http://127.0.0.1:8000/api/v1/advertisements/
Content-Type: application/json
#Authorization: Token 9fddd811b23a163f162333ffda01660a45652eec

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH http://127.0.0.1:8000/api/v1/advertisements/1/
Content-Type: application/json
Authorization: Token 65eee0f7a12cdb9e67b1eb08d8dc754c3e95ee3a

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET http://127.0.0.1:8000/api/v1/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET http://127.0.0.1:8000/api/v1/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
